CREATE TABLE supply (
    id INTEGER PRIMARY KEY,
    source TEXT,
    source_type TEXT,
    region TEXT,
    scenario TEXT,
    year INTEGER,
    start_month INTEGER,
    months_active INTEGER,
    profile TEXT,
    profile_weights_json TEXT,
    original_unit TEXT,
    original_value REAL,
    ghv_mmbtu_per_tonne REAL,
    cargo_mmbtu REAL,
    cargo_tonnes REAL,
    mtpa REAL,
    mmbtu REAL,
    cargoes REAL,
    equity_fraction REAL,
    equity_mtpa REAL,
    equity_mmbtu REAL,
    equity_cargoes REAL,
    notes TEXT
, status TEXT NOT NULL DEFAULT 'negotiation');
CREATE UNIQUE INDEX uq_supply_key ON supply(source,source_type,region,scenario,year);
CREATE TABLE opportunity (
    id INTEGER PRIMARY KEY,
    contract_name TEXT,
    counterparty TEXT,
    status TEXT,
    fob_des TEXT,
    pricing_index TEXT,
    region TEXT,
    year INTEGER,
    start_month INTEGER,
    months_active INTEGER,
    profile TEXT,
    profile_weights_json TEXT,
    original_unit TEXT,
    original_value REAL,
    ghv_mmbtu_per_tonne REAL,
    cargo_mmbtu REAL,
    cargo_tonnes REAL,
    mtpa REAL,
    mmbtu REAL,
    cargoes REAL,
    probability REAL,
    notes TEXT
);
CREATE UNIQUE INDEX uq_opportunity_key ON opportunity(contract_name,counterparty,year);
CREATE TABLE supply_monthly (
    id INTEGER PRIMARY KEY,
    source TEXT,
    source_type TEXT,
    region TEXT,
    scenario TEXT,
    year INTEGER,
    month INTEGER,
    value_mtpa REAL,
    value_mmbtu REAL,
    value_cargoes REAL,
    equity_value_mtpa REAL,
    equity_value_mmbtu REAL,
    equity_value_cargoes REAL
);
CREATE TABLE opportunity_monthly (
    id INTEGER PRIMARY KEY,
    contract_name TEXT,
    counterparty TEXT,
    status TEXT,
    region TEXT,
    year INTEGER,
    month INTEGER,
    value_mtpa REAL,
    value_mmbtu REAL,
    value_cargoes REAL,
    probability REAL
);
